version: 2.1
orbs:
    node: circleci/node@1.1.6
jobs:
    build-test-deploy:
        executor:
            name: node/default
        steps:
            - checkout
            - node/with-cache:
                  steps:
                      - run: npm install
                      - run: npm run-script build
                      - run: node .circleci/deploy.js
                      - run: echo "WE'RE ONLINE"
workflows:
    push:
        jobs:
            - build-test-deploy:
                filters:
                    branches:
                        only:
                            - master
